version: '3'

services:
  database:
    image: mysql/mysql-server:5.7.37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: stt_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: 123
    ports:
      - "9906:3306"
    volumes:
      - 'mysql_data:/data'

  web:
    build: .
    container_name: php_web
    depends_on:
      - database
    volumes:
      - .:/var/www/html/
    ports:
      - "8100:80"
    stdin_open: true
    tty: true

volumes:  
  mysql_data:
    driver: local  